### ISSUE TITLE
Failure to update model from oracle database using EF 5 and VS 2017

### ISSUE THREAD

**Issue by bilalMlaik** [oracle/dotnet-db-samples#2]
I have a C# application using Oracle database and Entity Framework 5. Oracle client is version 12c. My application uses database first approach. I'm trying to run the app using Visual Studio Professional 2017. When I access the edmx file and I try to update the model from the database, it gives me the following error

>  exception of type 'System.ArgumentException' occurred while attempting to update from the database. The exception message is: 'Unable to convert runtime connection string to its design-time equivalent. The libraries required to enable Visual Studio to communicate with the database for design purposes (DDEX provider) are not installed for provider 'Oracle.DataAccess.Client'. Connection string: XXXXX.

i have already installed oracle developer tool for visual studio 2017
Please help me to solve this issue

**Comment by alexkeh** [comment]
I believe the problem is that you haven't installed Oracle Developer Tools (ODT) for Visual Studio 2017.  ODT is necessary for EF DB First scenarios.

**Comment by bilalMlaik** [comment]
i fixed this issue by installing ODAC

**Comment by skidrou** [comment]
@bilalMlaik can you help me? What ODAC did you use? Have you had any other procedure? ODT or just ODAC? Pleaseeee, help me

**Comment by skidrou** [comment]
Just for helping someone, this solution worked for me: installed the version 12.2.0.1.0 of ODT and then after went to the folder C:\Program Files (x86)\Oracle Developer Tools for VS2017\odt and installed Oracle.VsDevTools.15.0.vsix. Fixed on VS 2017 Community

**Comment by sosam29** [comment]
Hi, Which version of  Visual Studio are you using? As I tried all the above suggestions and I am still having the same issue.

**Comment by yanjianyigaii** [comment]
> Hi, Which version of Visual Studio are you using? As I tried all the above suggestions and I am still having the same issue.

Same thing here. I had the latest version ODT installed for VS 2017 BUT GOT THE SAME ERROR WHEN UPDATING THE ENTITIES
