### ISSUE TITLE
ManagedDataAccess.Core - unpredictable pooling errors between operating systems

### ISSUE THREAD

**Issue by kamilzzz** [oracle/dotnet-db-samples#58]
Hello,

We're trying to use Oracle.ManagedDataAccess.Core with .NET Core 3.1 running on Linux (Debian 10) Docker container, but we're experiencing critical pooling errors. Docker host is Ubuntu 16.04.

### Environment:
Oracle.ManagedDataAccess.Core - 2.19.60
.NET Core - 3.1
Oracle database - 12.1.0.2 Standard Edition, running on Azure virtual machine
Azure public IP address configuration - drop idle TCP connections after 4 minutes of inactivity (default config).
Docker host operating system - Ubuntu 16.04
Container base image - Debian 10 (mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim)

### Expected behaviour:
After 4 minutes of inactivity, TCP connection to Oracle database is dropped, but provider can detect that and reconnects without errors and without significant delay.

### Actual behaviour:
When the connection is dropped and connection is returned from the pool for another operation the command that is about to be executed freezes for approx. 15 minutes and then throws ORA-12570 exception. 

### Code for reproducing error:
Waiting for 5 minutes to be sure Azure Load Balancer drops idle TCP connection to database.

Program.cs:
```
using System;
using System.Threading.Tasks;
using Oracle.ManagedDataAccess.Client;

namespace OracleTest
{
    class Program
    {
        static async Task Main(string[] args)
        {
            for (var i = 0; i < 100; i++)
            {
                await Select();
                Log("Waiting for 5:00m");
                await Task.Delay(TimeSpan.FromMinutes(5));
                Log("Wait ended");
            }
        }

        static async Task Select()
        {
            try
            {
                var connectionString = "Data Source=<azure-vm-ip>:1521/cdb1;User Id=<user>;Password=<pass>;";
                await using var connection = new OracleConnection(connectionString);

                await connection.OpenAsync();

                var selectCommand = new OracleCommand("select 'success' from dual", connection);
                Log("Sending command");
                var reader = (OracleDataReader)await selectCommand.ExecuteReaderAsync();
                Log("Command executed");
                while (await reader.ReadAsync())
                {
                    Log("Result " + reader.GetFieldValue<string>(0));
                }
                await reader.CloseAsync();
                Log("Reader closed");
            }
            catch (Exception e)
            {
                Log(e.Message);
            }
        }

        static void Log(string msg)
        {
            Console.WriteLine($"[{DateTime.Now.ToString("HH:mm:ss.fff")}] {msg}");
        }
    }
}
```
.csproj:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.9.10" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="2.19.60" />
  </ItemGroup>

</Project>
```

And now the weirdest part. **This behaviour varies between different configurations of operating system (details below).** 

### 1. Windows 10 1909 (Azure VM/local PC) - code running directly without Docker container

ORA-12570 thrown after ~15-20 seconds when provider tries to use dropped connection returned from pool.
Output:
```
[19:08:45.968] Sending command
[19:08:46.238] Command executed
[19:08:46.293] Result success
[19:08:46.298] Reader closed
[19:08:46.315] Waiting for 5:00m
[19:13:46.345] Wait ended
[19:13:46.354] Sending command
[19:14:07.973] ORA-12570: Network Session: Unexpected packet read error
```

**Works correctly when** `connection.KeepAlive = true`:
```
[19:31:07.841] Sending command
[19:31:08.017] Command executed
[19:31:08.041] Result success
[19:31:08.054] Reader closed
[19:31:08.087] Waiting for 5:00m
[19:36:08.094] Wait ended
[19:36:08.110] Sending command
[19:36:08.221] Command executed
[19:36:08.221] Result success
[19:36:08.221] Reader closed
[19:36:08.222] Waiting for 5:00m
```

### 2. Host - Windows 10 1909 (Azure VM/local PC) . Code running on Docker container using base image specified above (mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim)

The only configuration that works correctly. Application doesn't throw any errors.
This configuration can work for all day without throwing any error. 

Output:
```
[19:09:04.809] Sending command
[19:09:05.019] Command executed
[19:09:05.048] Result success
[19:09:05.064] Reader closed
[19:09:05.094] Waiting for 5:00m
[19:14:05.097] Wait ended
[19:14:05.113] Sending command
[19:14:05.236] Command executed
[19:14:05.236] Result success
[19:14:05.236] Reader closed
[19:14:05.237] Waiting for 5:00m
```

With `connection.KeepAlive = true` still works correctly (as expected):
```
[19:29:59.188] Sending command
[19:29:59.352] Command executed
[19:29:59.368] Result success
[19:29:59.373] Reader closed
[19:29:59.391] Waiting for 5:00m
[19:34:59.442] Wait ended
[19:34:59.453] Sending command
[19:34:59.559] Command executed
[19:34:59.559] Result success
[19:34:59.559] Reader closed
[19:34:59.560] Waiting for 5:00m
``` 

### 3. Ubuntu 16.04 (Azure VM) - code running directly without Docker container

ORA-12570 thrown after ~15-20 **minutes** when provider tries to use dropped connection returned from pool.
```
[19:12:00.083] Sending command
[19:12:00.138] Command executed
[19:12:00.283] Result success
[19:12:00.287] Reader closed
[19:12:00.299] Waiting for 5:00m
[19:17:00.300] Wait ended
[19:17:00.309] Sending command
[19:32:47.955] ORA-12570: Network Session: Unexpected packet read error
```

**Setting `connection.KeepAlive = true` doesn't change anything.**

```
[19:40:22.521] Sending command
[19:40:22.560] Command executed
[19:40:22.570] Result success
[19:40:22.574] Reader closed
[19:40:22.587] Waiting for 5:00m
[19:45:22.592] Wait ended
[19:45:22.603] Sending command
[20:01:09.841] ORA-12570: Network Session: Unexpected packet read error
```

### 4. Host - Ubuntu 16.04 (Azure VM). Code running on Docker container using base image specified above.

ORA-12570 thrown after ~15-20 **minutes** when provider tries to use dropped connection returned from pool.
```
[18:57:07.295] Sending command
[18:57:07.315] Command executed
[18:57:07.315] Result success
[18:57:07.315] Reader closed
[18:57:07.315] Waiting for 5:00m
[19:02:07.316] Wait ended
[19:02:07.317] Sending command
[19:17:58.290] ORA-12570: Network Session: Unexpected packet read error
```

**Setting `connection.KeepAlive = true` doesn't change anything.**

```
[19:36:07.779] Sending command
[19:36:07.821] Command executed
[19:36:07.832] Result success
[19:36:07.836] Reader closed
[19:36:07.849] Waiting for 5:00m
[19:41:07.850] Wait ended
[19:41:07.859] Sending command
[19:56:59.174] ORA-12570: Network Session: Unexpected packet read error
``` 

With pooling disabled the application doesn't freeze but that's not the way it should be fixed (with pooling disabled and high number of concurrent requests we're getting another error indicating that db cannot create more connections).

Any ideas why this works inconsistently and how to make pooling work correctly regardless of Docker host operating system?

**Comment by alexkeh** [comment]
According to the [Azure doc](https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-tcp-idle-timeout):

_In its default configuration, Azure Load Balancer has an idle timeout setting of 4 minutes. If a period of inactivity is longer than the timeout value, there's no guarantee that the TCP or HTTP session is maintained between the client and your cloud service._

I interpret that to mean 4 minutes is the idle connection minimum lifetime with no maximum. It's possible for a connection to live after 5 minutes of idle time, which could explain why the connection worked in Scenario 1 without using KeepAlive.

ODP.NET Core hasn't certified with Ubuntu. It supports Oracle Linux and Red Hat Linux currently. Oracle is considering future ODP.NET Ubuntu certification.

**Comment by kamilzzz** [comment]
Hello Alex, thanks for response.

I've tested ODP.NET Core on additional configurations:

- oraclelinux:7 container running on Windows 10 1909 host
- oraclelinux:7 container running on Ubuntu 16.04 host
- code running directly on oracle linux 7 host machine

This time all tests performed with `connection.KeepAlive = true`.
Results are similar to the ones I provided in initial issue description.

### 1. oraclelinux:7 container running on Windows 10 1909 host
Works correctly (the same as ubuntu/debian container running on Windows 10 1909 host)

Output:
```
[18:42:56.260] Sending command
[18:42:56.346] Command executed
[18:42:56.389] Result success
[18:42:56.405] Reader closed
[18:42:56.455] Waiting for 5:00m
[18:47:56.453] Wait ended
[18:47:56.478] Sending command
[18:47:56.525] Command executed
[18:47:56.525] Result success
[18:47:56.525] Reader closed
[18:47:56.525] Waiting for 5:00m
```

### 2. oraclelinux:7 container running on Ubuntu 16.04 host machine
Application freezes for ~15 **minutes.**

Output:
```
[18:53:55.036] Sending command
[18:53:55.087] Command executed
[18:53:55.097] Result success
[18:53:55.100] Reader closed
[18:53:55.112] Waiting for 5:00m
[18:58:55.115] Wait ended
[18:58:55.124] Sending command
[19:14:46.151] ORA-12570: Network Session: Unexpected packet read error
```

### 3. Code running directly on oracle linux 7 host machine (Azure VM)
Application freezes for **~15minutes.**

Output:
```
[19:31:10.365] Sending command
[19:31:10.466] Command executed
[19:31:10.496] Result success
[19:31:10.506] Reader closed
[19:31:10.533] Waiting for 5:00m
[19:36:10.548] Wait ended
[19:36:10.569] Sending command
[19:52:09.481] ORA-12570: Network Session: Unexpected packet read error
```

**Comment by alexkeh** [comment]
Well, it appears that whenever Ubuntu is the host KeepAlive isn't working as expected.

In your final scenario, do you have an ODP.NET trace (level 7) you can share? I can take a take a look as that scenario is supposed to work. If it's a large trace or one you don't want to post, you can email it to me alex.keh(at)oracle.com.

**Comment by kamilzzz** [comment]
I've emailed you the trace

**Comment by alexkeh** [comment]
@kamilzzz 

My team took another look at ODP.NET Core and .NET Core KeepAlive APIs. When ODP.NET Core added KeepAlive support last year, .NET Core 2 only had a Windows only for all the KeepAlive interfaces. We missed noting the Windows-only restriction in the Oracle doc. What you observe using Linux and ODPC is consistent with that.

Currently, my team is looking at the newly [.NET Core 3 KeepAlive APIs](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socketoptionname?view=netcore-3.0) that are cross-platform. If they behave as documented, ODP.NET Core will incorporate these in a future release to support KeepAlive on Linux.

**Comment by kamilzzz** [comment]
Thanks for the update.

Not working KeepAlive settings is one thing.

Another question is why on Windows it takes ~15-20 seconds to recover from dropped connection returned from pool, but on Linux it takes ~15 minutes (during that time the thread which asked for connection is blocked)?
Ideally I would expect on both systems provider should detect that connection is dropped and open new connection without significant delay (freezing for 15 seconds I would consider as a significant delay which affects application performance).
This seems to be unrelated to KeepAlive. Even with working KeepAlive I can imagine situation where TCP connection is dropped for whatever reason and then application would still freeze for 15 seconds on Windows and for 15 minutes on Linux.

**Comment by alexkeh** [comment]
Are you testing against the same DB instance with the same ODP.NET Core code and configuration?

**Comment by kamilzzz** [comment]
Yes. Exactly the same configuration.

Azure Oracle Db configured as shown here: https://docs.microsoft.com/pl-pl/azure/virtual-machines/workloads/oracle/oracle-database-quick-create

And the ODP.NET Core configuration is the standard one - using the code I posted in the issue description without any other changes.

And then when you look at case 1 in the issue description (code running directly on Windows) - ORA-12570 is thrown after 15seconds.
But when you look at the case 3 (this comment: https://github.com/oracle/dotnet-db-samples/issues/58#issuecomment-583584409) you will notice ORA-12570 is thrown after 15 minutes.

**Comment by alexkeh** [comment]
Hi @kamilzzz 
I followed up with my network engineer who knows much more about this topic than I. He says the time it takes to return a connection really depends on what the intermediary does when it times out the connection, and what the client is doing.

If the intermediary resets the connection to the **client**, and the client is in a receive, then they should see the "reset" immediately. But there are many things that could change that:

* The 15 secs could be part of the time the intermediary takes to time out the connection.

* The intermediary might not be resetting the connection and if he doesn't send anything to the client, the client could never see an error. If the client at some point sends a packet (which will happen when ODP.NET checks in/out from the pool), then the connection will see an error when that send times out. How long that takes is very OS dependent.

* Another variable here is how quickly the client app actually goes to the network (starts a new receive if not already in one).

**Comment by alexkeh** [comment]
As my team works on implementing cross-platform KeepAlive, a couple suggestions for working around the issue of firewalls killing idle ODP.NET connections.

1) Turn off connection pooling
2) Keep connection pooling, but set the Validate Connection attribute to true.

Validate Connection will pick up a connection from the pool. If the connection it finds is invalid, it will go back to the pool until it finds a valid connection before handing it off to the user.

**Comment by jtsoya539** [comment]
Hi @alexkeh 
Any news on cross-platform KeepAlive for ODP.NET Core?

Thanks

**Comment by alexkeh** [comment]
Cross-platform Keep Alive won't be in our next 19.8 patch release. We're trying to add it into one of our planned releases in the second half of this year.

**Comment by ganniaiuei** [comment]
Thank you for getting back, but sorry, onestly, this shouldn't be closed as the issue is not resolved yet.

**Comment by alexkeh** [comment]
@ganniaiuei 
The original problem/question filed by @kamilzzz has been answered and resolved. KeepAlive on Linux is a separate issue. My team continues work implementing it.

**Comment by ganniaiuei** [comment]
Hi @alexkeh
There are two new releases for the ODP.NET core at this moment (2.19.90 and 2.19.80).
One of those addresses the cross-platform KeepAlive for ODP.NET Core?

Thanks

**Comment by alexkeh** [comment]
@ganniaiuei 
No. However, it's looking like we will have a fix in the upcoming 19.10 version.

**Comment by rajsharmabannu** [comment]
Hey @alexkeh 
Can we know which version of the Oracle.ManagedDataAccess.Core does the 19.10 version correspond to?
Like mentioned by @ganniaiuei -  2.19.90 or 2.19.80 etc. ?


Also, this particular problem of ORA-12570, we never faced as much we are facing it now.

Had been using version 2.19.70 of Oracle.ManagedDataAccess.Core in DotNetCore 2.2 and it worked flawlessly but once we upgraded to DotNetCore 3.1, naturally saw the update in Nuget for 2.19.90 and updated the oracle driver too.

Soon after production deployment, we are facing this issue quite often. 
The data won't come sometimes but refreshing the window and calling the DB again, will get the data. 
Since it is not regular and very sporadic, it is causing a bad UX for our business too.

Can you please shed some light on what might be the issue and it's resolution too?

We deploy our apps on the cloud (Pivotal Cloud Foundry) with Linux containers, just FYI.

**Comment by alexkeh** [comment]
@rajsharmabannu  
For ODP.NET Core 19.10, the NuGet package will be 2.19.100. The last two set of digits refer to the actual product version. The first helps make it clear you will need a minimum .NET Core 2 version to use it.

I typically see ORA-12570 errors that are sporadic in cloud deployments when the firewall/load balancer's TCP idle timeout expires. It's usually set by default around 4-5 minutes depending on which cloud you use. I'm not familiar with Pivotal's default. If you changed your firewall or load balancer with the move to .NET Core 3.1 and connections are timing out after a set number of seconds idle, then the timeout is very likely your error source.

To resolve this type of error, you can change the timeout default to a higher value or you can use ODP.NET KeepAlive. Since you are running on Linux, you will need the upcoming ODP.NET 19.10 for KeepAlive to work on non-Windows platforms. Prior to that version, only Windows was supported.

**Comment by rajsharmabannu** [comment]
@alexkeh 
Thank you for the succinct explanation.

Just to give you some context -  we have been using .NetCore 3.1 with 2.19.70 and there was no problem till now when we actually started using 2.19.90.

Like I mentioned, we are facing this issue on the page-load of our application too. Some DB calls are made during the page load out of which few fail sometimes, and sometimes they work. It is not happening after 4-5 mins or anything as such. If it works, then for that period of time, every other DB call works too, or again, might fail if it wants to. There is no particular pattern that I can tell you of, that is the main problem. But I guess, the first few DB calls which fail, do not fall into the category you mentioned, right? 

We have no jurisdiction to change the firewall or any property of the load balancer of the cloud. It is managed by a specific team. **But is there anything from the .net core solution that is needed to be changed**?
Also, would you be able to tell me the exact thing that I can forward to our Cloud team to check upon? Or, do you need anything from their side to help us with this issue?


Lastly, can you tell us when's the proposed date of availability of 2.19.100 version?

**Comment by alexkeh** [comment]
@rajsharmabannu 
The 19.10 release will occur this month. We're wrapping up some testing. It could be released as early as this week.

Without a discernible pattern (and little understanding what your app is doing when it fails), I don't have any educated guesses. 

If the problem is the firewall and you can't change it, you can use the ODP.NET KeepAlive setting in your app to send a probe packet to ensure the connection isn't severed by the firewall. You can ask your firewall team what is the TCP timeout for idle connections they have set and can it be increased.

To track down the problem, open up a service request with Oracle Support to work on getting diagnostics needed to lock down the error pattern and isolate the possible root causes. If the problem happens early on, collect some ODP.NET traces for Oracle Support to compare a working situation vs. the one with errors.

**Comment by vijaysvs80** [comment]
@alexkeh Our team is going through exactly same issue -

We migrated our services from .net Standard framework to .Net core and moved to AWS Cloud. These services are hosted in Docker container (Linux Ubuntu) and orchestrated by Docker Swarm. 

We started encountering this sporadic oracle connection issues in Prod (We did not see this issue in Non-Prod environment). Our service is talking to Oracle DB  that is in vendor VPC over PrivateLink. After a week of investigation we found that there is a some issue with Connection pool.. If we turned off connection pool, service works fine.. with connection pool it blows oracle connection issues occasionally. 

I did talk to our Network Engineer. he said that Network Load balancer is resetting TCP connection after 350ms. I figured that's reason closed connection in the pool gets used by app request.

I came across this thread and updated the ODP.Net to 2.19.100 version and added below args to connection string

"KeepAlive=true;KeepAliveInterval=10;KeepAliveTime=60"

Updated Libs
		<PackageReference Include="Oracle.EntityFrameworkCore" Version="3.19.80" />
		<PackageReference Include="Oracle.ManagedDataAccess.Core" Version="2.19.100" />

However, we get following exception for some reason 


```
fail: Microsoft.EntityFrameworkCore.Database.Connection[0]
      2020-12-14 08:24:34.782236 ThreadID:5   (ERROR)   OracleCompositeMemberTranslator.CreateDbConnection() :  System.ArgumentException: 'KeepAlive' is an invalid connection string attribute
         at OracleInternal.ConnectionPool.ConnectionString.SetProperty(String key, String value, String quotedValue, String originalKey, SecureString secPasswd)
         at OracleInternal.ConnectionPool.ConnectionString.Parse(OracleConnection con, String constr)
         at OracleInternal.ConnectionPool.ConnectionString..ctor(OracleConnection con, String constring, OracleCredential credential)
         at OracleInternal.ConnectionPool.ConnectionString.GetCS(OracleConnection con, String constr, OracleCredential credential, Boolean bCreateIfNotinCache)
         at Oracle.ManagedDataAccess.Client.OracleConnection.set_ConnectionString(String value)
         at Oracle.ManagedDataAccess.Client.OracleConnection..ctor(String connectionString)
         at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalConnection.CreateDbConnection()
2020-12-14 08:24:34,790 ERROR Microsoft.EntityFrameworkCore.Database.Connection - 2020-12-14 08:24:34.782236 ThreadID:5   (ERROR)   OracleCompositeMemberTranslator.CreateDbConnection() :  System.ArgumentException: 'KeepAlive' is an invalid connection string attribute
   at OracleInternal.ConnectionPool.ConnectionString.SetProperty(String key, String value, String quotedValue, String originalKey, SecureString secPasswd)
   at OracleInternal.ConnectionPool.ConnectionString.Parse(OracleConnection con, String constr)
   at OracleInternal.ConnectionPool.ConnectionString..ctor(OracleConnection con, String constring, OracleCredential credential)
   at OracleInternal.ConnectionPool.ConnectionString.GetCS(OracleConnection con, String constr, OracleCredential credential, Boolean bCreateIfNotinCache)
   at Oracle.ManagedDataAccess.Client.OracleConnection.set_ConnectionString(String value)
   at Oracle.ManagedDataAccess.Client.OracleConnection..ctor(String connectionString)
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalConnection.CreateDbConnection()
fail: Microsoft.EntityFrameworkCore.Infrastructure[0]
      2020-12-14 08:24:34.794325 ThreadID:5   (ERROR)   OracleExecutionStrategy.Execute() :  System.ArgumentException: 'KeepAlive' is an invalid connection string attribute
         at OracleInternal.ConnectionPool.ConnectionString.SetProperty(String key, String value, String quotedValue, String originalKey, SecureString secPasswd)
         at OracleInternal.ConnectionPool.ConnectionString.Parse(OracleConnection con, String constr)
         at OracleInternal.ConnectionPool.ConnectionString..ctor(OracleConnection con, String constring, OracleCredential credential)
         at OracleInternal.ConnectionPool.ConnectionString.GetCS(OracleConnection con, String constr, OracleCredential credential, Boolean bCreateIfNotinCache)
         at Oracle.ManagedDataAccess.Client.OracleConnection.set_ConnectionString(String value)
         at Oracle.ManagedDataAccess.Client.OracleConnection..ctor(String connectionString)
         at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalConnection.CreateDbConnection()
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
         at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.CreateCommand(RelationalCommandParameterObject parameterObject, Guid commandId, DbCommandMethod commandMethod)
         at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
         at Oracle.EntityFrameworkCore.Storage.Internal.OracleExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
2020-12-14 08:24:34,796 ERROR Microsoft.EntityFrameworkCore.Infrastructure - 2020-12-14 08:24:34.794325 ThreadID:5   (ERROR)   OracleExecutionStrategy.Execute() :  System.ArgumentException: 'KeepAlive' is an invalid connection string attribute
   at OracleInternal.ConnectionPool.ConnectionString.SetProperty(String key, String value, String quotedValue, String originalKey, SecureString secPasswd)
   at OracleInternal.ConnectionPool.ConnectionString.Parse(OracleConnection con, String constr)
   at OracleInternal.ConnectionPool.ConnectionString..ctor(OracleConnection con, String constring, OracleCredential credential)
   at OracleInternal.ConnectionPool.ConnectionString.GetCS(OracleConnection con, String constr, OracleCredential credential, Boolean bCreateIfNotinCache)
   at Oracle.ManagedDataAccess.Client.OracleConnection.set_ConnectionString(String value)
   at Oracle.ManagedDataAccess.Client.OracleConnection..ctor(String connectionString)
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.CreateCommand(RelationalCommandParameterObject parameterObject, Guid commandId, DbCommandMethod commandMethod)
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'URTLInteract.Data.Models.URTLInteractModel'.
      System.ArgumentException: 'KeepAlive' is an invalid connection string attribute
         at OracleInternal.ConnectionPool.ConnectionString.SetProperty(String key, String value, String quotedValue, String originalKey, SecureString secPasswd)
         at OracleInternal.ConnectionPool.ConnectionString.Parse(OracleConnection con, String constr)
         at OracleInternal.ConnectionPool.ConnectionString..ctor(OracleConnection con, String constring, OracleCredential credential)
         at OracleInternal.ConnectionPool.ConnectionString.GetCS(OracleConnection con, String constr, OracleCredential credential, Boolean bCreateIfNotinCache)
         at Oracle.ManagedDataAccess.Client.OracleConnection.set_ConnectionString(String value)
         at Oracle.ManagedDataAccess.Client.OracleConnection..ctor(String connectionString)
         at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalConnection.CreateDbConnection()
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
         at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.CreateCommand(RelationalCommandParameterObject parameterObject, Guid commandId, DbCommandMethod commandMethod)
         at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
         at Oracle.EntityFrameworkCore.Storage.Internal.OracleExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
System.ArgumentException: 'KeepAlive' is an invalid connection string attribute
   at OracleInternal.ConnectionPool.ConnectionString.SetProperty(String key, String value, String quotedValue, String originalKey, SecureString secPasswd)
   at OracleInternal.ConnectionPool.ConnectionString.Parse(OracleConnection con, String constr)
   at OracleInternal.ConnectionPool.ConnectionString..ctor(OracleConnection con, String constring, OracleCredential credential)
   at OracleInternal.ConnectionPool.ConnectionString.GetCS(OracleConnection con, String constr, OracleCredential credential, Boolean bCreateIfNotinCache)
   at Oracle.ManagedDataAccess.Client.OracleConnection.set_ConnectionString(String value)
   at Oracle.ManagedDataAccess.Client.OracleConnection..ctor(String connectionString)
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.CreateCommand(RelationalCommandParameterObject parameterObject, Guid commandId, DbCommandMethod commandMethod)
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
2020-12-14 08:24:34,816 ERROR Microsoft.EntityFrameworkCore.Query - An exception occurred while iterating over the results of a query for context type 'URTLInteract.Data.Models.URTLInteractModel'.
System.ArgumentException: 'KeepAlive' is an invalid connection string attribute
   at OracleInternal.ConnectionPool.ConnectionString.SetProperty(String key, String value, String quotedValue, String originalKey, SecureString secPasswd)
   at OracleInternal.ConnectionPool.ConnectionString.Parse(OracleConnection con, String constr)
   at OracleInternal.ConnectionPool.ConnectionString..ctor(OracleConnection con, String constring, OracleCredential credential)
   at OracleInternal.ConnectionPool.ConnectionString.GetCS(OracleConnection con, String constr, OracleCredential credential, Boolean bCreateIfNotinCache)
   at Oracle.ManagedDataAccess.Client.OracleConnection.set_ConnectionString(String value)
   at Oracle.ManagedDataAccess.Client.OracleConnection..ctor(String connectionString)
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.CreateCommand(RelationalCommandParameterObject parameterObject, Guid commandId, DbCommandMethod commandMethod)
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
System.ArgumentException: 'KeepAlive' is an invalid connection string attribute
   at OracleInternal.ConnectionPool.ConnectionString.SetProperty(String key, String value, String quotedValue, String originalKey, SecureString secPasswd)
   at OracleInternal.ConnectionPool.ConnectionString.Parse(OracleConnection con, String constr)
   at OracleInternal.ConnectionPool.ConnectionString..ctor(OracleConnection con, String constring, OracleCredential credential)
   at OracleInternal.ConnectionPool.ConnectionString.GetCS(OracleConnection con, String constr, OracleCredential credential, Boolean bCreateIfNotinCache)
   at Oracle.ManagedDataAccess.Client.OracleConnection.set_ConnectionString(String value)
   at Oracle.ManagedDataAccess.Client.OracleConnection..ctor(String connectionString)
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.CreateCommand(RelationalCommandParameterObject parameterObject, Guid commandId, DbCommandMethod commandMethod)
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
2020-12-14 08:24:34,918 ERROR URTLInteract.Data.URTLProfile - System.ArgumentException: 'KeepAlive' is an invalid connection string attribute
   at OracleInternal.ConnectionPool.ConnectionString.SetProperty(String key, String value, String quotedValue, String originalKey, SecureString secPasswd)
   at OracleInternal.ConnectionPool.ConnectionString.Parse(OracleConnection con, String constr)
   at OracleInternal.ConnectionPool.ConnectionString..ctor(OracleConnection con, String constring, OracleCredential credential)
   at OracleInternal.ConnectionPool.ConnectionString.GetCS(OracleConnection con, String constr, OracleCredential credential, Boolean bCreateIfNotinCache)
   at Oracle.ManagedDataAccess.Client.OracleConnection.set_ConnectionString(String value)
   at Oracle.ManagedDataAccess.Client.OracleConnection..ctor(String connectionString)
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.CreateCommand(RelationalCommandParameterObject parameterObject, Guid commandId, DbCommandMethod commandMethod)
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Any[TSource](IQueryable`1 source, Expression`1 predicate)
```

**Comment by alexkeh** [comment]
The ODP.NET KeepAlive APIs are not connection string attributes. They are OracleConnection properties. You'll be able to use them by setting them as property values.

https://docs.oracle.com/en/database/oracle/oracle-data-access-components/19.3.2/odpnt/ConnectionProperties.html#GUID-8C3065D0-9EA1-4086-B8FD-2927703B006C

**Comment by vijaysvs80** [comment]
@alexkeh Thank you !! Is there any best practices around on how to override oracleConnection properties in EntityFramework ?

**Comment by alexkeh** [comment]
Yes, EF Core does not allow access to data provider specific APIs.

You can use the sqlnet.ora setting, SQLNET.EXPIRE_TIME, to set the ODP.NET equivalent of KeepAliveTime. I think the unit of measure is minutes for SQLNET.EXPIRE_TIME instead of seconds in ODP.NET.

To indicate where ODP.NET can find its sqlnet.ora file, you can set the Tns_Admin connection string attribute to the directory that has sqlnet.ora. Alternatively, you can put the file in your current working directory or set the directory in the OS/environment variable TNS_ADMIN.

**Comment by vijaysvs80** [comment]
Thank you @alexkeh

**Comment by AbdulMuqtadeer** [comment]
Any update on this issue ? Did this issue resolved now as part of new update ?

**Comment by alexkeh** [comment]
@AbdulMuqtadeer If you're asking about ODP.NET Core KeepAlive on Linux, that support was added starting in version 19.10.

**Comment by AbdulMuqtadeer** [comment]
I am having this issue on windows machine, where requests are using dropped connection and its failing. It is happening intermittently. I haven't set keep alive = true though. Using .net core 3. Is there not a way to resolve this issue without setting keep alive value as there are many places where we will have to make a change.

**Comment by alexkeh** [comment]
KeepAlive is most commonly used when a firewall or load balancer is killing idle connections. If the administrator disables this firewall/load balancer feature, you don't have to use KeepAlive.

I see this issue most often in cloud PaaS environments when customers no longer have the ability to configure the idle connection timeout or similar feature. The solution then is to pay for a more expensive PaaS web environment in which you can configure the idle connection timeout or use KeepAlive and stay with the current PaaS.

**Comment by AbdulMuqtadeer** [comment]
Thnaks alex. I have the ability to configure idle timeout on lthe load balancer, and it is set to 5 mins. And min pool size is set to 5 with validate connection to true. Do you think i should set the min pool size to 0 ?

**Comment by alexkeh** [comment]
IMO, you should not let the idle timeout dictate you app's resource usage and quality of service. The timeout is supposed to work for you. You are not supposed to work around it. I would recommend turning it off if you have no use for it.

In most cases you will not when using Oracle Fast Connection Failover (FCF). FCF will remove invalid connections automatically from the pool whenever a service, service member, database, or node fails. If your DBA has enabled FCF on the DB side, it's very likely your app can already use it since ODP.NET enables FCF on the client side by default.

When you use Validate Connection, there's an extra round trip that occurs before opening each connection. That will affect performance and resource usage for every user. If you set Min Pool Size to zero, you run the risk of a connection storm if many users try to connect at once after a period of low usage. This defeats a big reason apps use a connection pool.

**Comment by ksantoso** [comment]
> The ODP.NET KeepAlive APIs are not connection string attributes. They are OracleConnection properties. You'll be able to use them by setting them as property values.
> 
> https://docs.oracle.com/en/database/oracle/oracle-data-access-components/19.3.2/odpnt/ConnectionProperties.html#GUID-8C3065D0-9EA1-4086-B8FD-2927703B006C

Hi Alex. Do you have any suggestion on how to apply those properties without having to modify code in many places?
Currently I have the following statement in every method that needs access to DB:
`using(OracleConnection conn = new OracleConnection(_constring)) 
{  
     // other codes such as OracleCommand and and ExecuteNonQuery  
}`

Connection Pooling and ValidationConnection have been enabled via OracleConnectionStringBuilder.

**Comment by alexkeh** [comment]
@ksantoso You can set the SQLNET.EXPIRE_TIME in the app/web.config for managed ODP.NET or in sqlnet.ora. This paramter takes in values as minutes instead of KeepAliveTime, which takes seconds. If you want to use seconds with SQLNET.EXPIRE_TIME, you can use the following format in the .NET config file:

`<setting name=" SQLNET.EXPIRE_TIME" value="30 sec" />`

**Comment by ksantoso** [comment]
> @ksantoso You can set the SQLNET.EXPIRE_TIME in the app/web.config for managed ODP.NET or in sqlnet.ora. This paramter takes in values as minutes instead of KeepAliveTime, which takes seconds. If you want to use seconds with SQLNET.EXPIRE_TIME, you can use the following format in the .NET config file:
> 
> `<setting name=" SQLNET.EXPIRE_TIME" value="30 sec" />`

@alexkeh Just a little more question if you don't mind :)
Does the configuration above still applicable to ..Net Core? 
The app and web config files have been replaced by appsettings.json and we usually access the parameters using `IConfiguration` via Dependency Injection.
Is there any method that we need to call in order to let ODP.Net know about this parameter?

**Comment by alexkeh** [comment]
In the case of ODP.NET Core, you would have to use sqlnet.ora.

**Comment by bourbongoat** [comment]
> Yes, EF Core does not allow access to data provider specific APIs.
> 
> You can use the sqlnet.ora setting, SQLNET.EXPIRE_TIME, to set the ODP.NET equivalent of KeepAliveTime. I think the unit of measure is minutes for SQLNET.EXPIRE_TIME instead of seconds in ODP.NET.
> 
> To indicate where ODP.NET can find its sqlnet.ora file, you can set the Tns_Admin connection string attribute to the directory that has sqlnet.ora. Alternatively, you can put the file in your current working directory or set the directory in the OS/environment variable TNS_ADMIN.

@alexkeh Are you saying that Oracle.ManagedDataAccess.Core with Oracle.EntityFrameworkCore will look for a sqlnet.ora settings file in the working directory of the application and we can use that file to set these values?  Or with EF Core are we unable to adjust the keep alive?

**Comment by bfbcunha** [comment]
Hi, we have the same issue with Oracle.ManagedDataAccess.Core v3.21.130 in .net8 using alpine3.18 image.
```c#
    _connection = new OracleConnection(_options.Value.DbConnection)
    {
        KeepAlive = true,
        KeepAliveInterval = 2, //Default = 6
        KeepAliveTime = 20 //Default= 60
    };
``` 
Our firewall kills connections idle for more than 350s.
![image](https://github.com/oracle/dotnet-db-samples/assets/82239941/2d2b517f-669c-405e-8ef1-3521cf87051b)

**Comment by alexkeh** [comment]
@bfbcunha Can you share an ODP.NET trace with KeepAlive enabled and the firewall killing the connection?

The trace will tell us if KeepAlive probes are being sent after 20 seconds of inactivity.

**Comment by bfbcunha** [comment]
Hello @alexkeh, thanks for the quick reply, here is the requested trace, but I can't see any trace related with the keep alive probe, just the query timming out.
[Trace-e2fb0e-2024-01-17 08_42_07.json](https://github.com/oracle/dotnet-db-samples/files/13961340/Trace-e2fb0e-2024-01-17.08_42_07.json)

This is our current configuration
```c#
...
.AddOracleDataProviderInstrumentation(options =>
{
    options.EnableConnectionLevelAttributes = true;
    options.EnableOpenCloseTracing = EnableOpenCloseTracing.AllOpenClose;
    options.EnableDBRoundTripTracing = true;
    options.InstrumentOracleDataReaderRead = true;
    options.RecordException = true;
    options.SetDbStatementForText = true;

})
...
OracleConfiguration.TraceLevel = 7;
 _connection = new OracleConnection(_options.Value.Way4DbConnection)
 {
     KeepAlive = true,
     TnsAdmin = @".\"
 };
``` 
Also the sqlnet.ora file approach didn't work for us as well
```
SQLNET.EXPIRE_TIME=5
```

**Comment by alexkeh** [comment]
@bfbcunha The trace file should have an extension .trc and be a text file, not a JSON file. Did you set a OracleConfiguration.TraceFileLocation value to the directory where to output the trace?

**Comment by bfbcunha** [comment]
Sorry @alexkeh , I've sent the trace from OpenTelemetry exporter.
Since the trace file contains sensitive data I cannot send it completelly but here is a file with some parts of it.
In case you need more data or something specific, let me know.
[trace.txt](https://github.com/oracle/dotnet-db-samples/files/13990582/trace.txt)

**Comment by alexkeh** [comment]
You can email the full trace to dotnet_us(at)oracle.com or open an Oracle SR to provide us the trace.

For this particular issue, the entire trace between the last client and server communication on the connection and the error. We need to see what is happening (or not happening) during that time frame.

**Comment by ajith-ajmal** [comment]
Is this resolved ? I’m having a touch time dealing tns network packet reader error . Tried all way 
Keep alive 
Validate connection 
Increased connection life time close to my load balancer 4minutes
Nothing seems to work 
OS:alpine latest
App : Dotnet 6
Oracle managed data access.core version : 23.5.1

**Comment by alexkeh** [comment]
@ajith-ajmal There are many issues discussed on this thread. Not all of them are the same. Some of them are resolved.

With respect to your issue, you can send us a trace with some detail about how often and when you see the network packet error.

**Comment by ajith-ajmal** [comment]
@alexkeh  Thanks for your quick response , my issue is related to tns packet reader error after 15 minutes of timeout. 
Here is our flow App => Loadbalancer (idle timeout 4 minutes) => Oracle DB 

Let's say I run a small load test with the below scenarios 

| Scenario                       | Timing                                          | Outcome                                                                                          |
|--------------------------------|-------------------------------------------------|--------------------------------------------------------------------------------------------------|
| 1. Immediate Retest            | Within 4 minutes of the first load test         | No issues observed. The connections are still alive since they haven't hit the idle timeout of the load balancer. |
| 2. Retest After Short Idle     | Between 4 minutes and 20 minutes after the first load test | Errors occur. Connections have been terminated by the load balancer due to the idle timeout (4 mins), leading to issues when reusing stale connections. |
| 3. Retest After Extended Idle  | After 20 minutes                                | No issues observed. The connection pool has likely recycled stale connections or they have been reestablished. |

Also here's my pool settings .Pooling=true;Min Pool Size=0;Max Pool Size=50;Connection Timeout=45;Connection Lifetime=180; 
Additionally I implemented the keep alive => true in the code

**Comment by alexkeh** [comment]
@ajith-ajmal The first thing I'd like to check is whether those KeepAlive probes are being sent, when they are sent, and whether those probes are being acknowledged.

Send us your ODP.NET trace (use trace level 7) in the second scenario. That one will be the most informative.

**Comment by ajith-ajmal** [comment]
Hey @alexkeh  , I got the required info but before that here's the settings 
load balancer time out => 4 minutes
my pool settings => ;Pooling=true;Min Pool Size=8;Max Pool Size=100;Incr Pool Size=10;Decr Pool Size=10;Connection Timeout=45;Connection Lifetime=600;( have tested with 230 s,180 s of life time but still the same behavior)

Keep Alive Settings =>
using (var connection = new OracleConnection(_databaseConfiguration.Value.ConnectionString) { KeepAlive = true, KeepAliveInterval = 120, KeepAliveTime = 60})
During my testing I received the following exceptions 
DB connection timeout
tns packet reader exception
tns packet writer exception

 Mailing you the trace at dotnet_us@oracle.com . Kind of blocking our Prod , any quick help would be greatly appreciated.

**Comment by ksantoso** [comment]
@ajith-ajmal Hi, I just want to share a workaround from my end since I also encountered the same problem in Production environment where our firewall automatically drops idle connections after certain period.
I have applied the `ValidateConnection` and `KeepAlive` but still no success.

What actually worked for me is the implementation of a [Background Task](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-8.0&tabs=visual-studio). 
This task will call a simple query to Oracle such as `SELECT 1 FROM DUAL` every n-seconds.
Note that you will need to call the query for each kind of connection that you have. If you have for example 2 different connection strings to Oracle in your apps, then you need to call that query using those connections as well.
Otherwise the other connection that you left behind will encounter the same problem.

**Comment by alexkeh** [comment]
The ODP.NET test team found a regression in the ODP.NET Core 23ai KeepAlive implementation. This may be the source of the problem. A new bug (37054477) has been filed to track this issue.

ODP.NET Core 21c KeepAlive is working as expected.

**Comment by alexkeh** [comment]
Bug 37054477 has been fixed in ODP.NET 23.6.

**Comment by ksantoso** [comment]
Confirmed that the keep-alive issue has been resolved in version 23.6.0. The background-task workaround is not necessary anymore.
Thanks for the follow-up :)

**Comment by MartenOlofsson** [comment]
I have a webapp (dotnet 9) using Oracle.EntityFrameworkCore Version 9.23.60 which is referencing Oracle.ManagedDataAccess.Core Version 23.6.1. Running the app locally on windows works fine. Running the app in an azure linux app service throws ORA-12570 exception after the app has been idle/during startup, it takes about 15-16 minutes before the exception is thrown. However, after the initial request, everything works normally. 

This is my connectionstring:

user id=userID;password=pass;data source=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=something.com)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=something.com)))

Is there something missing in my settings to get rid of this issue?

**Comment by alexkeh** [comment]
@MartenOlofsson If the Azure firewall uses the default TCP timeout setting, which most do, and your connections have been idle for more than 4 minutes, you can use the ODP.NET KeepAlive settings to ensure the firewall doesn't kill your connections. The KeepAlive properties are OracleConnection class members.

**Comment by MartenOlofsson** [comment]
Thanks for the quick reply. Can that be configured using ef core?

```
options.UseOracle(connectionString,
        optionsBuilder =>
        {
            optionsBuilder.UseOracleSQLCompatibility(OracleSQLCompatibility.DatabaseVersion19);
            optionsBuilder.CommandTimeout(30);
        });
```

Or should I use an interceptor to modify the connection directly?

**Comment by alexkeh** [comment]
From a code perspective, you can set KeepAlive on the OracleConnection object if you reference ODP.NET directly in your EF Core app. 

From a configuration perspective, you can set [SQLNET.EXPIRE_TIME](https://docs.oracle.com/en/database/oracle/oracle-database/23/netrf/parameters-for-the-sqlnet.ora.html#GUID-1070805B-0703-457C-8D2E-4EEC26193E5F) in your sqlnet.ora for the interval you want KeepAlive to occur.
